DROP TABLE IF EXISTS JOB CASCADE;
DROP TABLE IF EXISTS TASK CASCADE;

-- JOB
CREATE TABLE JOB(
   ID serial NOT NULL,
   N_POWER smallint NOT NULL,
   SEED bigint NOT NULL,
   EPSILON_POWER smallint NOT NULL,
   START_DATE timestamp without time zone NOT NULL,
   FINISH_DATE timestamp without time zone NOT NULL,
   TASK_COUNTER varchar NOT NULL,
   POINTS_INSIDE varchar NOT NULL,
   CLIENT_PROXY varchar NOT NULL,
   REP_NUMBERS double precision NOT NULL,
   BATCH_SIZE int NOT NULL,
   PI varchar NOT NULL
);

ALTER TABLE JOB ADD CONSTRAINT JOB_PK PRIMARY KEY (ID);

-- TASK
CREATE TABLE TASK(
    ID serial NOT NULL,
    JOB_ID int NOT NULL,
    SEED bigint NOT NULL,
    BATCH_SIZE int NOT NULL,
    CREATE_DATE timestamp without time zone NOT NULL,
    STATE varchar NOT NULL,
    BATCH_NUMBER varchar NOT NULL,
    RESULT int NOT NULL,
    EPSILON_POWER smallint NOT NULL
);

ALTER TABLE TASK ADD CONSTRAINT TASK_PK PRIMARY KEY (ID);
ALTER TABLE TASK ADD CONSTRAINT TASK_FK FOREIGN KEY (JOB_ID) REFERENCES JOB(ID);