//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `PI.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Pi;

public interface PiControllerPrx extends com.zeroc.Ice.ObjectPrx
{
    default void calculatePi(PiRequest request, ClientPrx clientProxy)
    {
        calculatePi(request, clientProxy, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void calculatePi(PiRequest request, ClientPrx clientProxy, java.util.Map<String, String> context)
    {
        _iceI_calculatePiAsync(request, clientProxy, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> calculatePiAsync(PiRequest request, ClientPrx clientProxy)
    {
        return _iceI_calculatePiAsync(request, clientProxy, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> calculatePiAsync(PiRequest request, ClientPrx clientProxy, java.util.Map<String, String> context)
    {
        return _iceI_calculatePiAsync(request, clientProxy, context, false);
    }

    /**
     * @hidden
     * @param iceP_request -
     * @param iceP_clientProxy -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_calculatePiAsync(PiRequest iceP_request, ClientPrx iceP_clientProxy, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "calculatePi", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeValue(iceP_request);
                     ostr.writeProxy(iceP_clientProxy);
                     ostr.writePendingValues();
                 }, null);
        return f;
    }

    default Task getTask()
    {
        return getTask(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Task getTask(java.util.Map<String, String> context)
    {
        return _iceI_getTaskAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Task> getTaskAsync()
    {
        return _iceI_getTaskAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Task> getTaskAsync(java.util.Map<String, String> context)
    {
        return _iceI_getTaskAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Task> _iceI_getTaskAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Task> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getTask", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     final com.zeroc.IceInternal.Holder<Task> ret = new com.zeroc.IceInternal.Holder<>();
                     istr.readValue(v -> ret.value = v, Task.class);
                     istr.readPendingValues();
                     return ret.value;
                 });
        return f;
    }

    default void notifyResult(TaskResult taskResult)
    {
        notifyResult(taskResult, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void notifyResult(TaskResult taskResult, java.util.Map<String, String> context)
    {
        _iceI_notifyResultAsync(taskResult, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> notifyResultAsync(TaskResult taskResult)
    {
        return _iceI_notifyResultAsync(taskResult, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> notifyResultAsync(TaskResult taskResult, java.util.Map<String, String> context)
    {
        return _iceI_notifyResultAsync(taskResult, context, false);
    }

    /**
     * @hidden
     * @param iceP_taskResult -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_notifyResultAsync(TaskResult iceP_taskResult, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "notifyResult", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeValue(iceP_taskResult);
                     ostr.writePendingValues();
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PiControllerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), PiControllerPrx.class, _PiControllerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PiControllerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), PiControllerPrx.class, _PiControllerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PiControllerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), PiControllerPrx.class, _PiControllerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PiControllerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), PiControllerPrx.class, _PiControllerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static PiControllerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, PiControllerPrx.class, _PiControllerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static PiControllerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, PiControllerPrx.class, _PiControllerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default PiControllerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (PiControllerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default PiControllerPrx ice_adapterId(String newAdapterId)
    {
        return (PiControllerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default PiControllerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (PiControllerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default PiControllerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (PiControllerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default PiControllerPrx ice_invocationTimeout(int newTimeout)
    {
        return (PiControllerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default PiControllerPrx ice_connectionCached(boolean newCache)
    {
        return (PiControllerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default PiControllerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (PiControllerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default PiControllerPrx ice_secure(boolean b)
    {
        return (PiControllerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default PiControllerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (PiControllerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default PiControllerPrx ice_preferSecure(boolean b)
    {
        return (PiControllerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default PiControllerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (PiControllerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default PiControllerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (PiControllerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default PiControllerPrx ice_collocationOptimized(boolean b)
    {
        return (PiControllerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default PiControllerPrx ice_twoway()
    {
        return (PiControllerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default PiControllerPrx ice_oneway()
    {
        return (PiControllerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default PiControllerPrx ice_batchOneway()
    {
        return (PiControllerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default PiControllerPrx ice_datagram()
    {
        return (PiControllerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default PiControllerPrx ice_batchDatagram()
    {
        return (PiControllerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default PiControllerPrx ice_compress(boolean co)
    {
        return (PiControllerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default PiControllerPrx ice_timeout(int t)
    {
        return (PiControllerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default PiControllerPrx ice_connectionId(String connectionId)
    {
        return (PiControllerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default PiControllerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (PiControllerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Pi::PiController";
    }
}
