//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `PI.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Pi;

public class PiRequest extends com.zeroc.Ice.Value
{
    public PiRequest()
    {
    }

    public PiRequest(short nPower, long seed, short epsilonPower)
    {
        this.nPower = nPower;
        this.seed = seed;
        this.epsilonPower = epsilonPower;
    }

    public short nPower;

    public long seed;

    public short epsilonPower;

    public PiRequest clone()
    {
        return (PiRequest)super.clone();
    }

    public static String ice_staticId()
    {
        return "::Pi::PiRequest";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -1342131236L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeShort(nPower);
        ostr_.writeLong(seed);
        ostr_.writeShort(epsilonPower);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        nPower = istr_.readShort();
        seed = istr_.readLong();
        epsilonPower = istr_.readShort();
        istr_.endSlice();
    }
}
