//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `PI.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Pi;

public class TaskResult extends com.zeroc.Ice.Value
{
    public TaskResult()
    {
        this.jobId = "";
    }

    public TaskResult(String jobId, int pointsInside)
    {
        this.jobId = jobId;
        this.pointsInside = pointsInside;
    }

    public String jobId;

    public int pointsInside;

    public TaskResult clone()
    {
        return (TaskResult)super.clone();
    }

    public static String ice_staticId()
    {
        return "::Pi::TaskResult";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -231060091L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(jobId);
        ostr_.writeInt(pointsInside);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        jobId = istr_.readString();
        pointsInside = istr_.readInt();
        istr_.endSlice();
    }
}
