//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `PI.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Pi;

public class Task extends com.zeroc.Ice.Value
{
    public Task()
    {
    }

    public Task(int batchPoints, long seed)
    {
        this.batchPoints = batchPoints;
        this.seed = seed;
    }

    public int batchPoints;

    public long seed;

    public Task clone()
    {
        return (Task)super.clone();
    }

    public static String ice_staticId()
    {
        return "::Pi::Task";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -1073522127L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeInt(batchPoints);
        ostr_.writeLong(seed);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        batchPoints = istr_.readInt();
        seed = istr_.readLong();
        istr_.endSlice();
    }
}
